apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "steel-browser.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "steel-browser.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ include "steel-browser.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "steel-browser.name" . }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "steel-browser.name" . }}
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ if .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{ else }}{{ include "steel-browser.serviceAccountName" . }}{{ end }}
      containers:
        - name: api
          image: {{ .Values.api.image }}
          ports:
            - containerPort: {{ .Values.api.port }}
            - containerPort: {{ .Values.api.wsPort }}
          env:
            {{- range $key, $value := .Values.api.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
{{- toYaml .Values.api.resources | nindent 12 }}