{{- if .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "steel-browser.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ include "steel-browser.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
  annotations:
    {{- range $key, $value := .Values.ui.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ui.ingress.className | quote }}
  rules:
    {{- range .Values.ui.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "steel-browser.fullname" $. }}-ui
                port:
                  number: 80
    {{- end }}
  {{- if .Values.ui.ingress.tls }}
  tls:
    {{- range .Values.ui.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
