apiVersion: v1
kind: Service
metadata:
  name: {{ include "steel-browser.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ include "steel-browser.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "steel-browser.name" . }}
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.ui.port }}