apiVersion: v1
kind: Service
metadata:
  name: {{ include "steel-browser.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "steel-browser.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "steel-browser.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 3000
      targetPort: {{ .Values.api.port }}
    - name: ws
      port: 9223
      targetPort: {{ .Values.api.wsPort }}